name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install pip
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install package
        run: pip3 install . --break-system-packages
     
      - name: Run tests
        run: pytest events -vv
